#ifndef GAME_DEFINITIONS_H
#define GAME_DEFINITIONS_H

#define GAME_DART_TIME_MS    15
#define GAME_ENEMY_TIME_MS  400
#define GAME_HERO_TIME_MS    20

#define ENEMY_SLEEP_CYCLES_VALUE 5

#endif // GAME_DEFINITIONS_H
